# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18-Xe0hsSVISc5qq4rt-JtVIiIrdG6a_i
"""

def greet():
    print('Hello from advanced feature')

greet()